"""Document builder for ALLINAGENT.

Generates useful, specific documents based on the actual request
and project context rather than generic placeholders.
"""
from __future__ import annotations

from .tools import WorkspaceTools
from .website_builder import CreationSpec
from .inspector import Inspector


class DocumentBuilder:
    """Creates specific, useful documents from natural language requests."""

    def __init__(self, tools: WorkspaceTools) -> None:
        self.tools = tools
        self.inspector = Inspector(tools)

    def build_document(self, spec: CreationSpec, prompt: str) -> list[str]:
        """Create a document based on the request. Returns list of created files."""
        created: list[str] = []
        base = spec.target_path or spec.name
        text = prompt.lower()

        # Determine document type
        doc_type = self._detect_doc_type(text)

        if doc_type == "readme":
            content = self._generate_readme(spec, prompt)
            path = f"{base}/README.md"
        elif doc_type == "spec":
            content = self._generate_spec(spec, prompt)
            path = f"{base}/SPECIFICATION.md"
        elif doc_type == "guide":
            content = self._generate_guide(spec, prompt)
            path = f"{base}/GUIDE.md"
        elif doc_type == "manual":
            content = self._generate_manual(spec, prompt)
            path = f"{base}/MANUAL.md"
        elif doc_type == "changelog":
            content = self._generate_changelog(spec, prompt)
            path = f"{base}/CHANGELOG.md"
        elif doc_type == "plan":
            content = self._generate_project_plan(spec, prompt)
            path = f"{base}/PROJECT_PLAN.md"
        else:
            content = self._generate_generic(spec, prompt)
            path = f"{base}/DOCUMENT.md"

        result = self.tools.write_file(path, content)
        if "WRITE OK" in result:
            created.append(path)
        return created

    def _detect_doc_type(self, text: str) -> str:
        if "readme" in text:
            return "readme"
        if "spec" in text or "specification" in text:
            return "spec"
        if "guide" in text:
            return "guide"
        if "manual" in text:
            return "manual"
        if "changelog" in text or "changes" in text:
            return "changelog"
        if "plan" in text:
            return "plan"
        return "generic"

    def _inspect_project(self) -> str:
        """Get project inspection for context."""
        try:
            inspection = self.inspector.inspect()
            return inspection.summary()
        except Exception:
            return "Project inspection unavailable."

    def _generate_readme(self, spec: CreationSpec, prompt: str) -> str:
        """Generate a useful README based on the project and request."""
        inspection = self._inspect_project()
        name = spec.name.replace("-", " ").title()

        return f"""# {name}

{spec.requirements[0].capitalize() if spec.requirements else "A project created by ALLINAGENT."}

## Overview

This project was created based on the request: "{prompt}"

## Project Inspection

```
{inspection}
```

## Getting Started

### Prerequisites

- Python 3.10+
- Modern web browser (for web projects)

### Installation

```bash
# Clone or download the project
cd {spec.name}

# For Python projects:
pip install -e .

# For web projects:
# Open index.html in your browser, or serve locally:
python -m http.server 8000
```

## Usage

```bash
# Run the project
allinagent --workspace . analyze project

# View files
allinagent --workspace . list files

# Search
allinagent --workspace . find "keyword"
```

## Project Structure

```
{spec.name}/
├── README.md
├── ... (project files)
```

## Features

{chr(10).join(f"- {req}" for req in spec.requirements) or "- Core functionality"}

## Safety

- File operations are sandboxed to the workspace
- Writes require explicit permission
- Shell commands require explicit permission

## License

MIT License - See LICENSE file for details.

## Acknowledgments

Generated by ALLINAGENT v1.2.5 — an independent, local-first AI coding agent.
"""

    def _generate_spec(self, spec: CreationSpec, prompt: str) -> str:
        """Generate a technical specification."""
        return f"""# Technical Specification: {spec.name.replace("-", " ").title()}

## 1. Introduction

### Purpose
{prompt}

### Scope
This specification defines the architecture, components, and behavior of the {spec.name} project.

### Technology Stack
{chr(10).join(f"- {t}" for t in spec.requirements) or "- As specified in the request"}

## 2. Architecture

### Overview
The project follows a modular architecture with clear separation of concerns.

### Components

1. **Core Module** - Main logic and orchestration
2. **Tools Layer** - File operations, validation, safety
3. **Builder Layer** - Project creation and modification
4. **Memory Layer** - Persistent context storage
5. **CLI Layer** - User interface and interaction

### Data Flow

```
User Request
    |
    v
Request Analyzer
    |
    v
Planner / Loop
    |
    v
Tool Registry
    |
    v
Builders / Tools
    |
    v
Validators
    |
    v
Memory / Project Store
```

## 3. Requirements

### Functional Requirements

{chr(10).join(f"- FR{i+1}: {req}" for i, req in enumerate(spec.requirements)) or "- FR1: Core functionality"}

### Non-Functional Requirements

- NFR1: Python 3.10+ compatibility
- NFR2: No external dependencies for local mode
- NFR3: All file operations sandboxed
- NFR4: Path traversal protection
- NFR5: Safe-by-default execution

## 4. Safety

- Path sandbox enforced
- Write operations require --allow-write
- Shell operations require --allow-shell
- --dry-run disables all mutations
- Protected config files cannot be silently overwritten

## 5. Testing

- Unit tests for all major features
- Integration tests for creation workflows
- Safety tests for guardrails
- Regression tests for existing functionality

Generated by ALLINAGENT v1.2.5.
"""

    def _generate_guide(self, spec: CreationSpec, prompt: str) -> str:
        """Generate a user guide."""
        return f"""# User Guide: {spec.name.replace("-", " ").title()}

## Quick Start

1. Install ALLINAGENT:
   ```bash
   pip install -e .
   ```

2. Navigate to the project:
   ```bash
   cd {spec.name}
   ```

3. Run ALLINAGENT:
   ```bash
   allinagent
   ```

## Common Tasks

### Creating a Website
```bash
allinagent --allow-write "make me a dark gaming website"
```

### Creating a Game
```bash
allinagent --allow-write "make me a game"
```

### Creating a Script
```bash
allinagent --allow-write "create a script"
```

### Inspecting a Project
```bash
allinagent inspect
```

### Running Diagnostics
```bash
allinagent doctor
```

## Safety

- File writes require `--allow-write`
- Shell commands require `--allow-shell`
- Use `--dry-run` to preview without changes
- Use `--no-memory` to disable memory storage

## Troubleshooting

| Problem | Solution |
|---------|----------|
| "WRITE DENIED" | Add `--allow-write` flag |
| "SHELL DENIED" | Add `--allow-shell` flag |
| "Path escapes workspace" | Use `--workspace` to set correct path |
| Tests failing | Run `pip install -e .` then `pytest` |

Generated by ALLINAGENT v1.2.5.
"""

    def _generate_manual(self, spec: CreationSpec, prompt: str) -> str:
        """Generate a technical manual."""
        return f"""# Technical Manual: {spec.name.replace("-", " ").title()}

## Table of Contents

1. [Introduction](#introduction)
2. [Installation](#installation)
3. [Architecture](#architecture)
4. [Configuration](#configuration)
5. [Usage](#usage)
6. [Safety Model](#safety-model)
7. [Troubleshooting](#troubleshooting)
8. [API Reference](#api-reference)

## Introduction

{prompt}

## Installation

```bash
# Clone the repository
git clone https://github.com/user/{spec.name}.git
cd {spec.name}

# Install
pip install -e .

# Optional LLM support
pip install -e ".[llm]"
```

## Architecture

ALLINAGENT uses a layered architecture:

- **CLI Layer**: Argument parsing, REPL, commands
- **Agent Layer**: Request routing and orchestration
- **Intelligence Layer**: Request analysis, planning
- **Tool Layer**: Sandboxed file operations
- **Builder Layer**: Project creation (website, game, script, document)
- **Safety Layer**: Guardrails, validators, checkpoints
- **Memory Layer**: Project context and conversation history

## Configuration

### Environment Variables

| Variable | Description | Default |
|----------|-------------|---------|
| `ALLINAGENT_API_KEY` | API key for external model | None |
| `ALLINAGENT_BASE_URL` | Model endpoint URL | None |
| `ALLINAGENT_MODEL` | Model name | None |
| `NO_COLOR` | Disable colored output | Not set |

### Workspace Config

Create `.allinagent.toml`:
```toml
[allinagent]
# model = "gpt-4o"
# base_url = "https://api.openai.com/v1"
```

## Safety Model

ALLINAGENT is safe-by-default:

1. **Path Sandbox**: All operations confined to workspace
2. **Permission Gates**: Writes and shell require explicit flags
3. **Protected Files**: Config files cannot be silently overwritten
4. **Checkpoint System**: Snapshot before major changes
5. **Dangerous Command Detection**: Blocks rm -rf, mkfs, etc.

## Troubleshooting

See the User Guide for common issues.

## API Reference

### CLI Commands

- `allinagent init` - Scaffold workspace config
- `allinagent doctor` - Run diagnostics
- `allinagent inspect` - Inspect project
- `allinagent checkpoint` - Create checkpoint
- `allinagent rollback` - Rollback to checkpoint

Generated by ALLINAGENT v1.2.5.
"""

    def _generate_changelog(self, spec: CreationSpec, prompt: str) -> str:
        """Generate a changelog."""
        return f"""# Changelog

All notable changes to {spec.name.replace("-", " ").title()} will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/), and this project adheres to [Semantic Versioning](https://semver.org/).

## [1.2.5] - 2026-10-06

### Added
- Universal creation system (websites, games, scripts, documents)
- Project inspection and analysis
- Checkpoint and rollback system
- Autonomous build-test-fix loop
- Tool registry with unified schemas
- Improved website builder with multi-page support
- Enhanced game builder with enemies, health, score, levels
- Document builder for READMEs, specs, guides, manuals
- Project memory with architecture tracking
- Progress reporting during operations
- `--no-memory` flag to disable memory
- `inspect`, `checkpoint`, `rollback`, `changes`, `diff` commands
- Safety guardrails for destructive operations
- Validators for Python, JSON, TOML, HTML, CSS, JS

### Changed
- Improved CLI with better help, status, and error messages
- Enhanced REPL with project and checkpoint commands
- Expanded test suite to {spec.name}-specific tests

### Security
- Protected config files from silent overwrite
- Dangerous shell command detection and blocking
- Payment credential safety guidance
- Safe-by-default file operations

## [1.1.0] - 2026-10-06

### Added
- Universal creation system
- Website builder
- Project memory
- File operations (rename, move, delete, edit)
- Validators
- Guardrails
- Payment guidance

## [1.0.0] - 2026-10-06

### Added
- Local-first AI coding agent
- Deterministic offline intent engine
- Sandboxed workspace tools
- Interactive REPL
- Persistent conversation memory
- Optional OpenAI-compatible reasoning

Generated by ALLINAGENT v1.2.5.
"""

    def _generate_project_plan(self, spec: CreationSpec, prompt: str) -> str:
        """Generate a project plan."""
        return f"""# Project Plan: {spec.name.replace("-", " ").title()}

## Objective
{prompt}

## Scope
This plan outlines the development of the {spec.name} project, including milestones, deliverables, and timeline.

## Milestones

### Phase 1: Foundation (Complete)
- [x] Project structure
- [x] Core architecture
- [x] Safety model
- [x] Basic tools

### Phase 2: Creation System (Complete)
- [x] Website builder
- [x] Game builder
- [x] Document builder
- [x] Script builder

### Phase 3: Intelligence (Complete)
- [x] Request analysis
- [x] Project inspection
- [x] Checkpoint system
- [x] Autonomous loop

### Phase 4: Polish (In Progress)
- [ ] Enhanced validation
- [ ] Performance optimization
- [ ] Documentation
- [ ] Test coverage expansion

## Deliverables

1. Working project with all features
2. Comprehensive test suite
3. Documentation (README, guide, manual)
4. Safety report

## Risk Assessment

| Risk | Likelihood | Impact | Mitigation |
|------|-----------|--------|------------|
| File corruption | Low | High | Checkpoint/rollback system |
| Infinite loops | Low | Medium | Bounded iteration limits |
| Security exposure | Low | High | Sandboxed operations |

## Requirements

{chr(10).join(f"- {req}" for req in spec.requirements) or "- Core functionality as described"}

Generated by ALLINAGENT v1.2.5.
"""

    def _generate_generic(self, spec: CreationSpec, prompt: str) -> str:
        """Generate a generic document."""
        return f"""# {spec.name.replace("-", " ").title()}

Created based on: "{prompt}"

## Overview

This document was generated by ALLINAGENT v1.2.5 based on your request.

## Content

{chr(10).join(f"- {req}" for req in spec.requirements) or "Add your content here."}

## Notes

- Generated by ALLINAGENT v1.2.5
- Local-first, offline-capable
"""
